spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5201314
    url: jdbc:mysql:///newzaomengfactory?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: top.vx520.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    top:
      vx520:
        mapper: debug
httpurl: http://localhost:8080
#配置session
#        阿里云身份验证
ALIBABA_CLOUD_ACCESS_KEY_ID:
ALIBABA_CLOUD_ACCESS_KEY_SECRET:

